// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type MealPlansStatus string

const (
	MealPlansStatusDraft     MealPlansStatus = "draft"
	MealPlansStatusActive    MealPlansStatus = "active"
	MealPlansStatusCompleted MealPlansStatus = "completed"
	MealPlansStatusArchived  MealPlansStatus = "archived"
)

func (e *MealPlansStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MealPlansStatus(s)
	case string:
		*e = MealPlansStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MealPlansStatus: %T", src)
	}
	return nil
}

type NullMealPlansStatus struct {
	MealPlansStatus MealPlansStatus `json:"meal_plans_status"`
	Valid           bool            `json:"valid"` // Valid is true if MealPlansStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMealPlansStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MealPlansStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MealPlansStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMealPlansStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MealPlansStatus), nil
}

type Ingredient struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Category    sql.NullString `json:"category"`
	DefaultUnit sql.NullString `json:"default_unit"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type MealPlan struct {
	ID            int64               `json:"id"`
	UserID        int32               `json:"user_id"`
	WeekStartDate time.Time           `json:"week_start_date"`
	WeekEndDate   time.Time           `json:"week_end_date"`
	Status        NullMealPlansStatus `json:"status"`
	CreatedAt     sql.NullTime        `json:"created_at"`
	UpdatedAt     sql.NullTime        `json:"updated_at"`
}

type MealPlanItem struct {
	ID           int64          `json:"id"`
	MealPlanID   int64          `json:"meal_plan_id"`
	IngredientID int64          `json:"ingredient_id"`
	Quantity     string         `json:"quantity"`
	Unit         string         `json:"unit"`
	Notes        sql.NullString `json:"notes"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type MealPlanRecipe struct {
	ID                 int64          `json:"id"`
	MealPlanID         int64          `json:"meal_plan_id"`
	RecipeID           int64          `json:"recipe_id"`
	ServingsMultiplier sql.NullString `json:"servings_multiplier"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

type ProfileBauItem struct {
	ID           int64        `json:"id"`
	UserID       int32        `json:"user_id"`
	IngredientID int64        `json:"ingredient_id"`
	Quantity     string       `json:"quantity"`
	Unit         string       `json:"unit"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type ProfileMealPrepRecipe struct {
	ID         int64        `json:"id"`
	UserID     int32        `json:"user_id"`
	RecipeID   int64        `json:"recipe_id"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type ProfileRegularRecipe struct {
	ID               int64        `json:"id"`
	UserID           int32        `json:"user_id"`
	RecipeID         int64        `json:"recipe_id"`
	FrequencyPerWeek int32        `json:"frequency_per_week"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type Recipe struct {
	ID          int64          `json:"id"`
	UserID      int32          `json:"user_id"`
	Name        string         `json:"name"`
	Serves      int32          `json:"serves"`
	CanMealPrep bool           `json:"can_meal_prep"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RecipeIngredient struct {
	ID           int64          `json:"id"`
	RecipeID     int64          `json:"recipe_id"`
	IngredientID int64          `json:"ingredient_id"`
	Quantity     string         `json:"quantity"`
	Unit         string         `json:"unit"`
	Notes        sql.NullString `json:"notes"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type ShoppingList struct {
	ID          int64        `json:"id"`
	MealPlanID  int64        `json:"meal_plan_id"`
	GeneratedAt sql.NullTime `json:"generated_at"`
}

type ShoppingListItem struct {
	ID             int64          `json:"id"`
	ShoppingListID int64          `json:"shopping_list_id"`
	IngredientID   int64          `json:"ingredient_id"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	Checked        sql.NullBool   `json:"checked"`
	Category       sql.NullString `json:"category"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type User struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Created        time.Time `json:"created"`
}

type UserProfile struct {
	ID                   int64         `json:"id"`
	UserID               int32         `json:"user_id"`
	MealPrepRotationSize sql.NullInt32 `json:"meal_prep_rotation_size"`
	CreatedAt            sql.NullTime  `json:"created_at"`
	UpdatedAt            sql.NullTime  `json:"updated_at"`
}
