// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
	"database/sql"
)

type Querier interface {
	// ============================================================================
	// PROFILE BAU ITEMS
	// ============================================================================
	AddBAUItem(ctx context.Context, arg AddBAUItemParams) (sql.Result, error)
	// ============================================================================
	// RECIPE INGREDIENTS
	// ============================================================================
	AddIngredientToRecipe(ctx context.Context, arg AddIngredientToRecipeParams) (sql.Result, error)
	// ============================================================================
	// MEAL PLAN ITEMS
	// ============================================================================
	AddItemToMealPlan(ctx context.Context, arg AddItemToMealPlanParams) (sql.Result, error)
	// ============================================================================
	// SHOPPING LIST ITEMS
	// ============================================================================
	AddItemToShoppingList(ctx context.Context, arg AddItemToShoppingListParams) (sql.Result, error)
	// ============================================================================
	// PROFILE MEAL PREP RECIPES
	// ============================================================================
	AddMealPrepRecipe(ctx context.Context, arg AddMealPrepRecipeParams) (sql.Result, error)
	// ============================================================================
	// MEAL PLAN RECIPES
	// ============================================================================
	AddRecipeToMealPlan(ctx context.Context, arg AddRecipeToMealPlanParams) (sql.Result, error)
	// ============================================================================
	// PROFILE REGULAR RECIPES
	// ============================================================================
	AddRegularRecipe(ctx context.Context, arg AddRegularRecipeParams) (sql.Result, error)
	ClearShoppingList(ctx context.Context, shoppingListID int64) error
	// ============================================================================
	// INGREDIENTS
	// ============================================================================
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (sql.Result, error)
	// ============================================================================
	// MEAL PLANS
	// ============================================================================
	CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (sql.Result, error)
	// ============================================================================
	// RECIPES
	// ============================================================================
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (sql.Result, error)
	// ============================================================================
	// SHOPPING LISTS
	// ============================================================================
	CreateShoppingList(ctx context.Context, mealPlanID int64) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	// ============================================================================
	// USER PROFILE
	// ============================================================================
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (sql.Result, error)
	DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error
	DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error
	DeleteRecipeIngredient(ctx context.Context, arg DeleteRecipeIngredientParams) error
	DeleteShoppingList(ctx context.Context, mealPlanID int64) error
	GetIngredient(ctx context.Context, id int64) (Ingredient, error)
	GetIngredientByName(ctx context.Context, name string) (Ingredient, error)
	GetMealPlan(ctx context.Context, arg GetMealPlanParams) (MealPlan, error)
	GetMealPlanByWeek(ctx context.Context, arg GetMealPlanByWeekParams) (MealPlan, error)
	GetMealPlanItems(ctx context.Context, mealPlanID int64) ([]GetMealPlanItemsRow, error)
	GetMealPlanRecipes(ctx context.Context, mealPlanID int64) ([]GetMealPlanRecipesRow, error)
	GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error)
	GetRecipeIngredients(ctx context.Context, recipeID int64) ([]GetRecipeIngredientsRow, error)
	GetShoppingList(ctx context.Context, mealPlanID int64) (ShoppingList, error)
	GetShoppingListItems(ctx context.Context, shoppingListID int64) ([]GetShoppingListItemsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserProfile(ctx context.Context, userID int32) (UserProfile, error)
	ListBAUItems(ctx context.Context, userID int32) ([]ListBAUItemsRow, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListIngredientsByCategory(ctx context.Context, category sql.NullString) ([]Ingredient, error)
	ListMealPlans(ctx context.Context, userID int32) ([]MealPlan, error)
	ListMealPrepRecipes(ctx context.Context, userID int32) ([]Recipe, error)
	ListMealPrepRecipesPool(ctx context.Context, userID int32) ([]ListMealPrepRecipesPoolRow, error)
	ListRecipesByUser(ctx context.Context, userID int32) ([]Recipe, error)
	ListRegularRecipes(ctx context.Context, userID int32) ([]ListRegularRecipesRow, error)
	RemoveBAUItem(ctx context.Context, arg RemoveBAUItemParams) error
	RemoveItemFromMealPlan(ctx context.Context, arg RemoveItemFromMealPlanParams) error
	RemoveMealPrepRecipe(ctx context.Context, arg RemoveMealPrepRecipeParams) error
	RemoveRecipeFromMealPlan(ctx context.Context, arg RemoveRecipeFromMealPlanParams) error
	RemoveRegularRecipe(ctx context.Context, arg RemoveRegularRecipeParams) error
	ToggleShoppingListItem(ctx context.Context, arg ToggleShoppingListItemParams) error
	UpdateBAUItem(ctx context.Context, arg UpdateBAUItemParams) error
	UpdateMealPlanItem(ctx context.Context, arg UpdateMealPlanItemParams) error
	UpdateMealPlanRecipeServings(ctx context.Context, arg UpdateMealPlanRecipeServingsParams) error
	UpdateMealPlanStatus(ctx context.Context, arg UpdateMealPlanStatusParams) error
	UpdateMealPrepRecipeLastUsed(ctx context.Context, arg UpdateMealPrepRecipeLastUsedParams) error
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) error
	UpdateRecipeIngredient(ctx context.Context, arg UpdateRecipeIngredientParams) error
	UpdateRegularRecipeFrequency(ctx context.Context, arg UpdateRegularRecipeFrequencyParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
