// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const addBAUItem = `-- name: AddBAUItem :execresult

INSERT INTO profile_bau_items (user_id, ingredient_id, quantity, unit)
VALUES (?, ?, ?, ?)
`

type AddBAUItemParams struct {
	UserID       int32  `json:"user_id"`
	IngredientID int64  `json:"ingredient_id"`
	Quantity     string `json:"quantity"`
	Unit         string `json:"unit"`
}

// ============================================================================
// PROFILE BAU ITEMS
// ============================================================================
func (q *Queries) AddBAUItem(ctx context.Context, arg AddBAUItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addBAUItem,
		arg.UserID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
}

const addIngredientToRecipe = `-- name: AddIngredientToRecipe :execresult

INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit, notes)
VALUES (?, ?, ?, ?, ?)
`

type AddIngredientToRecipeParams struct {
	RecipeID     int64          `json:"recipe_id"`
	IngredientID int64          `json:"ingredient_id"`
	Quantity     string         `json:"quantity"`
	Unit         string         `json:"unit"`
	Notes        sql.NullString `json:"notes"`
}

// ============================================================================
// RECIPE INGREDIENTS
// ============================================================================
func (q *Queries) AddIngredientToRecipe(ctx context.Context, arg AddIngredientToRecipeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addIngredientToRecipe,
		arg.RecipeID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		arg.Notes,
	)
}

const addItemToMealPlan = `-- name: AddItemToMealPlan :execresult

INSERT INTO meal_plan_items (meal_plan_id, ingredient_id, quantity, unit, notes)
VALUES (?, ?, ?, ?, ?)
`

type AddItemToMealPlanParams struct {
	MealPlanID   int64          `json:"meal_plan_id"`
	IngredientID int64          `json:"ingredient_id"`
	Quantity     string         `json:"quantity"`
	Unit         string         `json:"unit"`
	Notes        sql.NullString `json:"notes"`
}

// ============================================================================
// MEAL PLAN ITEMS
// ============================================================================
func (q *Queries) AddItemToMealPlan(ctx context.Context, arg AddItemToMealPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addItemToMealPlan,
		arg.MealPlanID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		arg.Notes,
	)
}

const addItemToShoppingList = `-- name: AddItemToShoppingList :execresult

INSERT INTO shopping_list_items (shopping_list_id, ingredient_id, quantity, unit, category)
VALUES (?, ?, ?, ?, ?)
`

type AddItemToShoppingListParams struct {
	ShoppingListID int64          `json:"shopping_list_id"`
	IngredientID   int64          `json:"ingredient_id"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	Category       sql.NullString `json:"category"`
}

// ============================================================================
// SHOPPING LIST ITEMS
// ============================================================================
func (q *Queries) AddItemToShoppingList(ctx context.Context, arg AddItemToShoppingListParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addItemToShoppingList,
		arg.ShoppingListID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		arg.Category,
	)
}

const addMealPrepRecipe = `-- name: AddMealPrepRecipe :execresult

INSERT INTO profile_meal_prep_recipes (user_id, recipe_id)
VALUES (?, ?)
`

type AddMealPrepRecipeParams struct {
	UserID   int32 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

// ============================================================================
// PROFILE MEAL PREP RECIPES
// ============================================================================
func (q *Queries) AddMealPrepRecipe(ctx context.Context, arg AddMealPrepRecipeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addMealPrepRecipe, arg.UserID, arg.RecipeID)
}

const addRecipeToMealPlan = `-- name: AddRecipeToMealPlan :execresult

INSERT INTO meal_plan_recipes (meal_plan_id, recipe_id, servings_multiplier)
VALUES (?, ?, ?)
`

type AddRecipeToMealPlanParams struct {
	MealPlanID         int64          `json:"meal_plan_id"`
	RecipeID           int64          `json:"recipe_id"`
	ServingsMultiplier sql.NullString `json:"servings_multiplier"`
}

// ============================================================================
// MEAL PLAN RECIPES
// ============================================================================
func (q *Queries) AddRecipeToMealPlan(ctx context.Context, arg AddRecipeToMealPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addRecipeToMealPlan, arg.MealPlanID, arg.RecipeID, arg.ServingsMultiplier)
}

const addRegularRecipe = `-- name: AddRegularRecipe :execresult

INSERT INTO profile_regular_recipes (user_id, recipe_id, frequency_per_week)
VALUES (?, ?, ?)
`

type AddRegularRecipeParams struct {
	UserID           int32 `json:"user_id"`
	RecipeID         int64 `json:"recipe_id"`
	FrequencyPerWeek int32 `json:"frequency_per_week"`
}

// ============================================================================
// PROFILE REGULAR RECIPES
// ============================================================================
func (q *Queries) AddRegularRecipe(ctx context.Context, arg AddRegularRecipeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addRegularRecipe, arg.UserID, arg.RecipeID, arg.FrequencyPerWeek)
}

const clearShoppingList = `-- name: ClearShoppingList :exec
DELETE FROM shopping_list_items
WHERE shopping_list_id = ?
`

func (q *Queries) ClearShoppingList(ctx context.Context, shoppingListID int64) error {
	_, err := q.db.ExecContext(ctx, clearShoppingList, shoppingListID)
	return err
}

const createIngredient = `-- name: CreateIngredient :execresult

INSERT INTO ingredients (name, category, default_unit)
VALUES (?, ?, ?)
`

type CreateIngredientParams struct {
	Name        string         `json:"name"`
	Category    sql.NullString `json:"category"`
	DefaultUnit sql.NullString `json:"default_unit"`
}

// ============================================================================
// INGREDIENTS
// ============================================================================
func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIngredient, arg.Name, arg.Category, arg.DefaultUnit)
}

const createMealPlan = `-- name: CreateMealPlan :execresult

INSERT INTO meal_plans (user_id, week_start_date, week_end_date, status)
VALUES (?, ?, ?, ?)
`

type CreateMealPlanParams struct {
	UserID        int32               `json:"user_id"`
	WeekStartDate time.Time           `json:"week_start_date"`
	WeekEndDate   time.Time           `json:"week_end_date"`
	Status        NullMealPlansStatus `json:"status"`
}

// ============================================================================
// MEAL PLANS
// ============================================================================
func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMealPlan,
		arg.UserID,
		arg.WeekStartDate,
		arg.WeekEndDate,
		arg.Status,
	)
}

const createRecipe = `-- name: CreateRecipe :execresult

INSERT INTO recipes (user_id, name, serves, can_meal_prep, notes)
VALUES (?, ?, ?, ?, ?)
`

type CreateRecipeParams struct {
	UserID      int32          `json:"user_id"`
	Name        string         `json:"name"`
	Serves      int32          `json:"serves"`
	CanMealPrep bool           `json:"can_meal_prep"`
	Notes       sql.NullString `json:"notes"`
}

// ============================================================================
// RECIPES
// ============================================================================
func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecipe,
		arg.UserID,
		arg.Name,
		arg.Serves,
		arg.CanMealPrep,
		arg.Notes,
	)
}

const createShoppingList = `-- name: CreateShoppingList :execresult

INSERT INTO shopping_lists (meal_plan_id)
VALUES (?)
`

// ============================================================================
// SHOPPING LISTS
// ============================================================================
func (q *Queries) CreateShoppingList(ctx context.Context, mealPlanID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, createShoppingList, mealPlanID)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (name, email, hashed_password, created)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Created        time.Time `json:"created"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.Created,
	)
}

const createUserProfile = `-- name: CreateUserProfile :execresult

INSERT INTO user_profile (user_id, meal_prep_rotation_size)
VALUES (?, ?)
`

type CreateUserProfileParams struct {
	UserID               int32         `json:"user_id"`
	MealPrepRotationSize sql.NullInt32 `json:"meal_prep_rotation_size"`
}

// ============================================================================
// USER PROFILE
// ============================================================================
func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserProfile, arg.UserID, arg.MealPrepRotationSize)
}

const deleteMealPlan = `-- name: DeleteMealPlan :exec
DELETE FROM meal_plans
WHERE id = ? AND user_id = ?
`

type DeleteMealPlanParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error {
	_, err := q.db.ExecContext(ctx, deleteMealPlan, arg.ID, arg.UserID)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = ? AND user_id = ?
`

type DeleteRecipeParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, arg.ID, arg.UserID)
	return err
}

const deleteRecipeIngredient = `-- name: DeleteRecipeIngredient :exec
DELETE FROM recipe_ingredients
WHERE recipe_id = ? AND ingredient_id = ?
`

type DeleteRecipeIngredientParams struct {
	RecipeID     int64 `json:"recipe_id"`
	IngredientID int64 `json:"ingredient_id"`
}

func (q *Queries) DeleteRecipeIngredient(ctx context.Context, arg DeleteRecipeIngredientParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeIngredient, arg.RecipeID, arg.IngredientID)
	return err
}

const deleteShoppingList = `-- name: DeleteShoppingList :exec
DELETE FROM shopping_lists
WHERE meal_plan_id = ?
`

func (q *Queries) DeleteShoppingList(ctx context.Context, mealPlanID int64) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingList, mealPlanID)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, category, default_unit, created_at, updated_at FROM ingredients
WHERE id = ?
`

func (q *Queries) GetIngredient(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientByName = `-- name: GetIngredientByName :one
SELECT id, name, category, default_unit, created_at, updated_at FROM ingredients
WHERE name = ?
`

func (q *Queries) GetIngredientByName(ctx context.Context, name string) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredientByName, name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlan = `-- name: GetMealPlan :one
SELECT id, user_id, week_start_date, week_end_date, status, created_at, updated_at FROM meal_plans
WHERE id = ? AND user_id = ?
`

type GetMealPlanParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetMealPlan(ctx context.Context, arg GetMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getMealPlan, arg.ID, arg.UserID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanByWeek = `-- name: GetMealPlanByWeek :one
SELECT id, user_id, week_start_date, week_end_date, status, created_at, updated_at FROM meal_plans
WHERE user_id = ? AND week_start_date = ?
`

type GetMealPlanByWeekParams struct {
	UserID        int32     `json:"user_id"`
	WeekStartDate time.Time `json:"week_start_date"`
}

func (q *Queries) GetMealPlanByWeek(ctx context.Context, arg GetMealPlanByWeekParams) (MealPlan, error) {
	row := q.db.QueryRowContext(ctx, getMealPlanByWeek, arg.UserID, arg.WeekStartDate)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealPlanItems = `-- name: GetMealPlanItems :many
SELECT mpi.id, mpi.meal_plan_id, mpi.ingredient_id, mpi.quantity, mpi.unit, mpi.notes, mpi.created_at, i.name as ingredient_name, i.category
FROM meal_plan_items mpi
JOIN ingredients i ON mpi.ingredient_id = i.id
WHERE mpi.meal_plan_id = ?
`

type GetMealPlanItemsRow struct {
	ID             int64          `json:"id"`
	MealPlanID     int64          `json:"meal_plan_id"`
	IngredientID   int64          `json:"ingredient_id"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	IngredientName string         `json:"ingredient_name"`
	Category       sql.NullString `json:"category"`
}

func (q *Queries) GetMealPlanItems(ctx context.Context, mealPlanID int64) ([]GetMealPlanItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMealPlanItems, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealPlanItemsRow
	for rows.Next() {
		var i GetMealPlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.Notes,
			&i.CreatedAt,
			&i.IngredientName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealPlanRecipes = `-- name: GetMealPlanRecipes :many
SELECT mpr.id, mpr.meal_plan_id, mpr.recipe_id, mpr.servings_multiplier, mpr.created_at, r.name as recipe_name, r.serves, r.can_meal_prep
FROM meal_plan_recipes mpr
JOIN recipes r ON mpr.recipe_id = r.id
WHERE mpr.meal_plan_id = ?
`

type GetMealPlanRecipesRow struct {
	ID                 int64          `json:"id"`
	MealPlanID         int64          `json:"meal_plan_id"`
	RecipeID           int64          `json:"recipe_id"`
	ServingsMultiplier sql.NullString `json:"servings_multiplier"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	RecipeName         string         `json:"recipe_name"`
	Serves             int32          `json:"serves"`
	CanMealPrep        bool           `json:"can_meal_prep"`
}

func (q *Queries) GetMealPlanRecipes(ctx context.Context, mealPlanID int64) ([]GetMealPlanRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMealPlanRecipes, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealPlanRecipesRow
	for rows.Next() {
		var i GetMealPlanRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.RecipeID,
			&i.ServingsMultiplier,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Serves,
			&i.CanMealPrep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, user_id, name, serves, can_meal_prep, notes, created_at, updated_at FROM recipes
WHERE id = ? AND user_id = ?
`

type GetRecipeParams struct {
	ID     int64 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetRecipe(ctx context.Context, arg GetRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, arg.ID, arg.UserID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Serves,
		&i.CanMealPrep,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeIngredients = `-- name: GetRecipeIngredients :many
SELECT ri.id, ri.recipe_id, ri.ingredient_id, ri.quantity, ri.unit, ri.notes, ri.created_at, i.name as ingredient_name, i.category
FROM recipe_ingredients ri
JOIN ingredients i ON ri.ingredient_id = i.id
WHERE ri.recipe_id = ?
`

type GetRecipeIngredientsRow struct {
	ID             int64          `json:"id"`
	RecipeID       int64          `json:"recipe_id"`
	IngredientID   int64          `json:"ingredient_id"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	IngredientName string         `json:"ingredient_name"`
	Category       sql.NullString `json:"category"`
}

func (q *Queries) GetRecipeIngredients(ctx context.Context, recipeID int64) ([]GetRecipeIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeIngredientsRow
	for rows.Next() {
		var i GetRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.Notes,
			&i.CreatedAt,
			&i.IngredientName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShoppingList = `-- name: GetShoppingList :one
SELECT id, meal_plan_id, generated_at FROM shopping_lists
WHERE meal_plan_id = ?
`

func (q *Queries) GetShoppingList(ctx context.Context, mealPlanID int64) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, getShoppingList, mealPlanID)
	var i ShoppingList
	err := row.Scan(&i.ID, &i.MealPlanID, &i.GeneratedAt)
	return i, err
}

const getShoppingListItems = `-- name: GetShoppingListItems :many
SELECT sli.id, sli.shopping_list_id, sli.ingredient_id, sli.quantity, sli.unit, sli.checked, sli.category, sli.created_at, i.name as ingredient_name
FROM shopping_list_items sli
JOIN ingredients i ON sli.ingredient_id = i.id
WHERE sli.shopping_list_id = ?
ORDER BY sli.category, i.name
`

type GetShoppingListItemsRow struct {
	ID             int64          `json:"id"`
	ShoppingListID int64          `json:"shopping_list_id"`
	IngredientID   int64          `json:"ingredient_id"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	Checked        sql.NullBool   `json:"checked"`
	Category       sql.NullString `json:"category"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	IngredientName string         `json:"ingredient_name"`
}

func (q *Queries) GetShoppingListItems(ctx context.Context, shoppingListID int64) ([]GetShoppingListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getShoppingListItems, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShoppingListItemsRow
	for rows.Next() {
		var i GetShoppingListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.Checked,
			&i.Category,
			&i.CreatedAt,
			&i.IngredientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, hashed_password, created FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Created,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, hashed_password, created FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Created,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, user_id, meal_prep_rotation_size, created_at, updated_at FROM user_profile
WHERE user_id = ?
`

func (q *Queries) GetUserProfile(ctx context.Context, userID int32) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealPrepRotationSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBAUItems = `-- name: ListBAUItems :many
SELECT pbi.id, pbi.user_id, pbi.ingredient_id, pbi.quantity, pbi.unit, pbi.created_at, i.name as ingredient_name, i.category
FROM profile_bau_items pbi
JOIN ingredients i ON pbi.ingredient_id = i.id
WHERE pbi.user_id = ?
`

type ListBAUItemsRow struct {
	ID             int64          `json:"id"`
	UserID         int32          `json:"user_id"`
	IngredientID   int64          `json:"ingredient_id"`
	Quantity       string         `json:"quantity"`
	Unit           string         `json:"unit"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	IngredientName string         `json:"ingredient_name"`
	Category       sql.NullString `json:"category"`
}

func (q *Queries) ListBAUItems(ctx context.Context, userID int32) ([]ListBAUItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBAUItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBAUItemsRow
	for rows.Next() {
		var i ListBAUItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.IngredientName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, category, default_unit, created_at, updated_at FROM ingredients
ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.DefaultUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByCategory = `-- name: ListIngredientsByCategory :many
SELECT id, name, category, default_unit, created_at, updated_at FROM ingredients
WHERE category = ?
ORDER BY name
`

func (q *Queries) ListIngredientsByCategory(ctx context.Context, category sql.NullString) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.DefaultUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlans = `-- name: ListMealPlans :many
SELECT id, user_id, week_start_date, week_end_date, status, created_at, updated_at FROM meal_plans
WHERE user_id = ?
ORDER BY week_start_date DESC
`

func (q *Queries) ListMealPlans(ctx context.Context, userID int32) ([]MealPlan, error) {
	rows, err := q.db.QueryContext(ctx, listMealPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealPlan
	for rows.Next() {
		var i MealPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStartDate,
			&i.WeekEndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPrepRecipes = `-- name: ListMealPrepRecipes :many
SELECT id, user_id, name, serves, can_meal_prep, notes, created_at, updated_at FROM recipes
WHERE user_id = ? AND can_meal_prep = TRUE
ORDER BY name
`

func (q *Queries) ListMealPrepRecipes(ctx context.Context, userID int32) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listMealPrepRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Serves,
			&i.CanMealPrep,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPrepRecipesPool = `-- name: ListMealPrepRecipesPool :many
SELECT pmr.id, pmr.user_id, pmr.recipe_id, pmr.last_used_at, pmr.created_at, r.name as recipe_name, r.serves
FROM profile_meal_prep_recipes pmr
JOIN recipes r ON pmr.recipe_id = r.id
WHERE pmr.user_id = ?
ORDER BY ISNULL(pmr.last_used_at), pmr.last_used_at ASC
`

type ListMealPrepRecipesPoolRow struct {
	ID         int64        `json:"id"`
	UserID     int32        `json:"user_id"`
	RecipeID   int64        `json:"recipe_id"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
	RecipeName string       `json:"recipe_name"`
	Serves     int32        `json:"serves"`
}

func (q *Queries) ListMealPrepRecipesPool(ctx context.Context, userID int32) ([]ListMealPrepRecipesPoolRow, error) {
	rows, err := q.db.QueryContext(ctx, listMealPrepRecipesPool, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealPrepRecipesPoolRow
	for rows.Next() {
		var i ListMealPrepRecipesPoolRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipeID,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Serves,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByUser = `-- name: ListRecipesByUser :many
SELECT id, user_id, name, serves, can_meal_prep, notes, created_at, updated_at FROM recipes
WHERE user_id = ?
ORDER BY name
`

func (q *Queries) ListRecipesByUser(ctx context.Context, userID int32) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Serves,
			&i.CanMealPrep,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegularRecipes = `-- name: ListRegularRecipes :many
SELECT prr.id, prr.user_id, prr.recipe_id, prr.frequency_per_week, prr.created_at, r.name as recipe_name, r.serves, r.can_meal_prep
FROM profile_regular_recipes prr
JOIN recipes r ON prr.recipe_id = r.id
WHERE prr.user_id = ?
`

type ListRegularRecipesRow struct {
	ID               int64        `json:"id"`
	UserID           int32        `json:"user_id"`
	RecipeID         int64        `json:"recipe_id"`
	FrequencyPerWeek int32        `json:"frequency_per_week"`
	CreatedAt        sql.NullTime `json:"created_at"`
	RecipeName       string       `json:"recipe_name"`
	Serves           int32        `json:"serves"`
	CanMealPrep      bool         `json:"can_meal_prep"`
}

func (q *Queries) ListRegularRecipes(ctx context.Context, userID int32) ([]ListRegularRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegularRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegularRecipesRow
	for rows.Next() {
		var i ListRegularRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipeID,
			&i.FrequencyPerWeek,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Serves,
			&i.CanMealPrep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBAUItem = `-- name: RemoveBAUItem :exec
DELETE FROM profile_bau_items
WHERE user_id = ? AND ingredient_id = ?
`

type RemoveBAUItemParams struct {
	UserID       int32 `json:"user_id"`
	IngredientID int64 `json:"ingredient_id"`
}

func (q *Queries) RemoveBAUItem(ctx context.Context, arg RemoveBAUItemParams) error {
	_, err := q.db.ExecContext(ctx, removeBAUItem, arg.UserID, arg.IngredientID)
	return err
}

const removeItemFromMealPlan = `-- name: RemoveItemFromMealPlan :exec
DELETE FROM meal_plan_items
WHERE id = ? AND meal_plan_id = ?
`

type RemoveItemFromMealPlanParams struct {
	ID         int64 `json:"id"`
	MealPlanID int64 `json:"meal_plan_id"`
}

func (q *Queries) RemoveItemFromMealPlan(ctx context.Context, arg RemoveItemFromMealPlanParams) error {
	_, err := q.db.ExecContext(ctx, removeItemFromMealPlan, arg.ID, arg.MealPlanID)
	return err
}

const removeMealPrepRecipe = `-- name: RemoveMealPrepRecipe :exec
DELETE FROM profile_meal_prep_recipes
WHERE user_id = ? AND recipe_id = ?
`

type RemoveMealPrepRecipeParams struct {
	UserID   int32 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

func (q *Queries) RemoveMealPrepRecipe(ctx context.Context, arg RemoveMealPrepRecipeParams) error {
	_, err := q.db.ExecContext(ctx, removeMealPrepRecipe, arg.UserID, arg.RecipeID)
	return err
}

const removeRecipeFromMealPlan = `-- name: RemoveRecipeFromMealPlan :exec
DELETE FROM meal_plan_recipes
WHERE meal_plan_id = ? AND recipe_id = ?
`

type RemoveRecipeFromMealPlanParams struct {
	MealPlanID int64 `json:"meal_plan_id"`
	RecipeID   int64 `json:"recipe_id"`
}

func (q *Queries) RemoveRecipeFromMealPlan(ctx context.Context, arg RemoveRecipeFromMealPlanParams) error {
	_, err := q.db.ExecContext(ctx, removeRecipeFromMealPlan, arg.MealPlanID, arg.RecipeID)
	return err
}

const removeRegularRecipe = `-- name: RemoveRegularRecipe :exec
DELETE FROM profile_regular_recipes
WHERE user_id = ? AND recipe_id = ?
`

type RemoveRegularRecipeParams struct {
	UserID   int32 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

func (q *Queries) RemoveRegularRecipe(ctx context.Context, arg RemoveRegularRecipeParams) error {
	_, err := q.db.ExecContext(ctx, removeRegularRecipe, arg.UserID, arg.RecipeID)
	return err
}

const toggleShoppingListItem = `-- name: ToggleShoppingListItem :exec
UPDATE shopping_list_items
SET checked = ?
WHERE id = ? AND shopping_list_id = ?
`

type ToggleShoppingListItemParams struct {
	Checked        sql.NullBool `json:"checked"`
	ID             int64        `json:"id"`
	ShoppingListID int64        `json:"shopping_list_id"`
}

func (q *Queries) ToggleShoppingListItem(ctx context.Context, arg ToggleShoppingListItemParams) error {
	_, err := q.db.ExecContext(ctx, toggleShoppingListItem, arg.Checked, arg.ID, arg.ShoppingListID)
	return err
}

const updateBAUItem = `-- name: UpdateBAUItem :exec
UPDATE profile_bau_items
SET quantity = ?, unit = ?
WHERE user_id = ? AND ingredient_id = ?
`

type UpdateBAUItemParams struct {
	Quantity     string `json:"quantity"`
	Unit         string `json:"unit"`
	UserID       int32  `json:"user_id"`
	IngredientID int64  `json:"ingredient_id"`
}

func (q *Queries) UpdateBAUItem(ctx context.Context, arg UpdateBAUItemParams) error {
	_, err := q.db.ExecContext(ctx, updateBAUItem,
		arg.Quantity,
		arg.Unit,
		arg.UserID,
		arg.IngredientID,
	)
	return err
}

const updateMealPlanItem = `-- name: UpdateMealPlanItem :exec
UPDATE meal_plan_items
SET quantity = ?, unit = ?, notes = ?
WHERE id = ? AND meal_plan_id = ?
`

type UpdateMealPlanItemParams struct {
	Quantity   string         `json:"quantity"`
	Unit       string         `json:"unit"`
	Notes      sql.NullString `json:"notes"`
	ID         int64          `json:"id"`
	MealPlanID int64          `json:"meal_plan_id"`
}

func (q *Queries) UpdateMealPlanItem(ctx context.Context, arg UpdateMealPlanItemParams) error {
	_, err := q.db.ExecContext(ctx, updateMealPlanItem,
		arg.Quantity,
		arg.Unit,
		arg.Notes,
		arg.ID,
		arg.MealPlanID,
	)
	return err
}

const updateMealPlanRecipeServings = `-- name: UpdateMealPlanRecipeServings :exec
UPDATE meal_plan_recipes
SET servings_multiplier = ?
WHERE meal_plan_id = ? AND recipe_id = ?
`

type UpdateMealPlanRecipeServingsParams struct {
	ServingsMultiplier sql.NullString `json:"servings_multiplier"`
	MealPlanID         int64          `json:"meal_plan_id"`
	RecipeID           int64          `json:"recipe_id"`
}

func (q *Queries) UpdateMealPlanRecipeServings(ctx context.Context, arg UpdateMealPlanRecipeServingsParams) error {
	_, err := q.db.ExecContext(ctx, updateMealPlanRecipeServings, arg.ServingsMultiplier, arg.MealPlanID, arg.RecipeID)
	return err
}

const updateMealPlanStatus = `-- name: UpdateMealPlanStatus :exec
UPDATE meal_plans
SET status = ?
WHERE id = ? AND user_id = ?
`

type UpdateMealPlanStatusParams struct {
	Status NullMealPlansStatus `json:"status"`
	ID     int64               `json:"id"`
	UserID int32               `json:"user_id"`
}

func (q *Queries) UpdateMealPlanStatus(ctx context.Context, arg UpdateMealPlanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMealPlanStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateMealPrepRecipeLastUsed = `-- name: UpdateMealPrepRecipeLastUsed :exec
UPDATE profile_meal_prep_recipes
SET last_used_at = ?
WHERE user_id = ? AND recipe_id = ?
`

type UpdateMealPrepRecipeLastUsedParams struct {
	LastUsedAt sql.NullTime `json:"last_used_at"`
	UserID     int32        `json:"user_id"`
	RecipeID   int64        `json:"recipe_id"`
}

func (q *Queries) UpdateMealPrepRecipeLastUsed(ctx context.Context, arg UpdateMealPrepRecipeLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateMealPrepRecipeLastUsed, arg.LastUsedAt, arg.UserID, arg.RecipeID)
	return err
}

const updateRecipe = `-- name: UpdateRecipe :exec
UPDATE recipes
SET name = ?, serves = ?, can_meal_prep = ?, notes = ?
WHERE id = ? AND user_id = ?
`

type UpdateRecipeParams struct {
	Name        string         `json:"name"`
	Serves      int32          `json:"serves"`
	CanMealPrep bool           `json:"can_meal_prep"`
	Notes       sql.NullString `json:"notes"`
	ID          int64          `json:"id"`
	UserID      int32          `json:"user_id"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipe,
		arg.Name,
		arg.Serves,
		arg.CanMealPrep,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateRecipeIngredient = `-- name: UpdateRecipeIngredient :exec
UPDATE recipe_ingredients
SET quantity = ?, unit = ?, notes = ?
WHERE recipe_id = ? AND ingredient_id = ?
`

type UpdateRecipeIngredientParams struct {
	Quantity     string         `json:"quantity"`
	Unit         string         `json:"unit"`
	Notes        sql.NullString `json:"notes"`
	RecipeID     int64          `json:"recipe_id"`
	IngredientID int64          `json:"ingredient_id"`
}

func (q *Queries) UpdateRecipeIngredient(ctx context.Context, arg UpdateRecipeIngredientParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipeIngredient,
		arg.Quantity,
		arg.Unit,
		arg.Notes,
		arg.RecipeID,
		arg.IngredientID,
	)
	return err
}

const updateRegularRecipeFrequency = `-- name: UpdateRegularRecipeFrequency :exec
UPDATE profile_regular_recipes
SET frequency_per_week = ?
WHERE user_id = ? AND recipe_id = ?
`

type UpdateRegularRecipeFrequencyParams struct {
	FrequencyPerWeek int32 `json:"frequency_per_week"`
	UserID           int32 `json:"user_id"`
	RecipeID         int64 `json:"recipe_id"`
}

func (q *Queries) UpdateRegularRecipeFrequency(ctx context.Context, arg UpdateRegularRecipeFrequencyParams) error {
	_, err := q.db.ExecContext(ctx, updateRegularRecipeFrequency, arg.FrequencyPerWeek, arg.UserID, arg.RecipeID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profile
SET meal_prep_rotation_size = ?
WHERE user_id = ?
`

type UpdateUserProfileParams struct {
	MealPrepRotationSize sql.NullInt32 `json:"meal_prep_rotation_size"`
	UserID               int32         `json:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.MealPrepRotationSize, arg.UserID)
	return err
}
